### PR TITLE
changes for July 2023 meeting

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by JoanneBogart** [comment]
Comparing to the previous checklist, I see that the DC2 section has been removed as Seth suggested. I'm wondering about the Rubin Science Platform item - is that gone because it also is primarily used for access to (reprocessed) DC2 data?  The item about jupyter kernels is also gone.  I don't object - it seemed oddly specific - but I'm wondering what the rationale was for removing it this time around.

**Review by JoanneBogart — APPROVED** [review]
LGTM

**Comment by jchiang87** [comment]
@EiffL Could you approve and/or merge this please?

**Review by yymao — APPROVED** [review]
Note: I didn't actually review this PR, but am approving since it has been reviewed but the reviewer didn't have write access to this repo.

**Comment by burchat** [comment]
@jchiang87  - I have a couple of suggestions for additions to the meeting checklist for the July meeting, in case one or both of these are appropriate for the spirit of the "meeting checklist" -- 

- Sign up [here](https://docs.google.com/spreadsheets/d/15dH9-URP6NXegRNgmD6KvDMHLnDEx0ToKmjGzz7jjqQ/edit?usp=sharing) for a walking tour to the LSST camera and a SLAC overlook on Monday or Wednesday.

- If you plan to attend DE School, please add your name, career stage, and affiliation to the [in-person or remote participant lists](https://confluence.slac.stanford.edu/display/LSSTDESC/July+2023+DESC+Meeting%3A+DE+School#July2023DESCMeeting:DESchool-Self-registration) at the bottom of the [DE School confluence page](https://confluence.slac.stanford.edu/x/zc2DFg).  (This helps with DE School planning and provides useful information when we apply for financial support and/or thank entities who provide support.)

**Comment by jchiang87** [comment]
Hi Pat, I can add these items.  I'll make a new PR with these additions.

**Pull request merged**
