### PR TITLE
add items for LSSTCam/SLAC tour and DE School

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by JoanneBogart** [comment]
LGTM

**Comment by villarrealas** [comment]
I'm a little biased, but I suggest removing preferred from being in front of pronouns in a few places (and possibly resourcing an article about pronouns use). I find the "preferred" language gives a sense of "optional" that I don't quite like.

Edit: For clarity, this is on a click through explaining pronouns, not directly on the checklist for this PR.

**Review by burchat — COMMENTED** [review]
I'm not sure why, but the direct link to the confluence signup for DE School in-person or remote participation (https://confluence.slac.stanford.edu/x/zc2DFg#July2023DESCMeeting:DESchool-Self-registration) doesn't work (for me) in the preview checklist link Jim posted in slack: https://htmlpreview.github.io/?https://github.com/LSSTDESC/pre-meeting-checklist/blob/u/jchiang/july_2023_additions/index.html#July2023DESCMeeting:DESchool-Self-registration

**Comment by jchiang87** [comment]
> I'm not sure why, but the direct link to the confluence signup for DE School in-person or remote participation (https://confluence.slac.stanford.edu/x/zc2DFg#July2023DESCMeeting:DESchool-Self-registration) doesn't work (for me) in the preview checklist link Jim posted in slack: https://htmlpreview.github.io/?https://github.com/LSSTDESC/pre-meeting-checklist/blob/u/jchiang/july_2023_additions/index.html#July2023DESCMeeting:DESchool-Self-registration

**Comment by jchiang87** [comment]
> I'm not sure why, but the direct link to the confluence signup for DE School in-person or remote participation (https://confluence.slac.stanford.edu/x/zc2DFg#July2023DESCMeeting:DESchool-Self-registration) doesn't work (for me) in the preview checklist link Jim posted in slack: https://htmlpreview.github.io/?https://github.com/LSSTDESC/pre-meeting-checklist/blob/u/jchiang/july_2023_additions/index.html#July2023DESCMeeting:DESchool-Self-registration

It worked for me when I previewed the file directly through my browser, but indeed the link doesn't work for me either from the preview page.  I wanted to use the permanent shareable link, but maybe adding the anchor to the sign up section is causing problems.  I'll put the full link in to see if that helps.

**Comment by jchiang87** [comment]
The full link still doesn't work, but I think this an issue with the preview page using `htmlpreview.github.io` that we've seen before.  I'm fairly certain it will be fine once deployed.

**Review by sethdigel — APPROVED** [review]
I agree that this looks good.  Thank you, Jim & Pat.

**Pull request merged**
